default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
        exclude: (^|/)\.vscode(/.*|$)|.*tsconfig.* # json5
      - id: check-yaml
        args:
          - --unsafe
        exclude: pnpm-lock.yaml
      - id: end-of-file-fixer
        exclude: .*\/schemas\/.*\.json # generated automatically by `tauri-cli`
      - id: trailing-whitespace
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.19.0
    hooks:
      - id: commitlint
        # NOTE, TODO, FIXME: DO NOT enable for `manual` stage (for now),
        # because `.git/COMMIT_EDITMSG` does not exist in CI
        stages: [commit-msg]
        # NOTE: the dependencies must consistent with `commitlint.config.js`
        additional_dependencies: ["@commitlint/config-conventional"]
  - repo: local
    hooks:
      # ref: <https://github.com/astral-sh/uv-pre-commit/blob/97775dd8479651d7bc0f21fc2d0b960de1ef6267/.pre-commit-hooks.yaml#L11-L20>
      - id: uv-lock
        name: update uv lockfile
        language: system
        entry: uv lock
        pass_filenames: false
        # # TODO, FIXME: This 'files' regex might be incorrect,
        # # sometimes this hook does not trigger.
        # # For now, we comment it out to always run this hook as workaround.
        # files: ^(uv\.lock|pyproject\.toml|uv\.toml)$
        stages: [pre-commit, manual]
      - id: pnpm-lock
        name: update pnpm lockfile
        language: system
        entry: pnpm install -r --lockfile-only
        pass_filenames: false
        # files: ^(pnpm-lock\.yaml|pnpm-workspace\.yaml|package\.json)$ # TODO
        stages: [pre-commit, manual]

      # NOTE: We do not need, nor have `cargo lock`.
      # `cargo check/build` will automatically update `Cargo.lock`.

      - id: python-fmt
        name: python format
        language: script
        entry: scripts/python-fmt.sh
        pass_filenames: false
        types: [python]
        stages: [pre-commit, manual]
      - id: rust-fmt
        name: rust format
        language: system
        entry: cargo fmt --all
        pass_filenames: false
        types: [rust]
        stages: [pre-commit, manual]
      - id: typos
        name: typos
        language: system
        entry: typos -w
        pass_filenames: false
        stages: [pre-commit, manual]

      # TODO, FIXME: typescript fmt

      - id: python-type-check
        name: python type check
        language: system
        entry: pnpm pyright .
        pass_filenames: false
        types: [python]
        stages: [pre-commit, manual]

      - id: python-verifytypes
        name: python verifytypes
        language: script
        entry: scripts/python-verifytypes.sh
        pass_filenames: false
        types: [python]
        stages: [manual] # because it's slow
      - id: cargo-clippy # rustup component add clippy
        name: cargo clippy
        language: system
        entry: cargo clippy --workspace --exclude=pytauri-test --all-features -- -D warnings
        pass_filenames: false
        types: [rust]
        stages: [manual] # because it's slow

      # 1. Check if TypeScript can compile successfully (typescript check).
      # 2. Check if the JS build dist snapshot tracked for the crate is updated,
      #    such as `tauri-plugin-pytauri/guest-js/dist/api-iife.*.js`.
      # NOTE: Keep this step after `cargo build/clippy` to check that
      # all dist snapshot required for the crate are tracked
      # (because if something missing, the compile will fail, then we will know).
      - id: pnpm-build-snapshot
        name: pnpm build snapshot
        language: system
        entry: pnpm -r build
        pass_filenames: false
        types_or: [javascript, jsx, ts, tsx]
        stages: [manual] # because it's slow

      - id: python-test
        name: python test
        language: script
        entry: scripts/python-test.sh
        pass_filenames: false
        types: [python]
        stages: [manual] # because it's slow
      - id: rust-unit-test
        name: rust unit test
        language: system
        entry: cargo test --workspace --exclude=pytauri-test --all-features
        pass_filenames: false
        types: [rust]
        stages: [manual] # because it's slow
      # NOTE: we cannot run this test when the `pytauri/__no_test` feature is enabled
      # (i.e., with --all-features), so we separate it into a standalone hook.
      # See `required-features` section of its `Cargo.toml` also.
      - id: rust-integration-test
        name: rust integration test
        language: system
        entry: cargo test -p pytauri-test --features="test"
        pass_filenames: false
        types: [rust]
        stages: [manual] # because it's slow

      # TODO, FIXME: rust doc check
