packages:
  - "packages/*"
  - "examples/tauri-app"
  - "examples/tauri-app-wheel"
  - "crates/tauri-plugin-pytauri/guest-js"

catalog:
  "@tauri-apps/cli": ^2.8
  "@tauri-apps/api": ^2.8
  "@tauri-apps/plugin-opener": ^2.5
  "@tauri-apps/plugin-dialog": ^2.3

catalogMode: prefer
