/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type JavaScriptChannelIdRootModelDatetime = string
export type RootModelNoneType = null
export type Name = string
export type RootModelStr = string

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
start_timer: {
input: JavaScriptChannelIdRootModelDatetime
output: RootModelNoneType
}
greet: {
input: Person
output: RootModelStr
}
}
export interface Person {
name: Name
}
