/* eslint-disable */
/**
* This file was automatically generated by pytauri-gen-ts.
* DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
* and run pytauri-gen-ts to regenerate this file.
*/

import { pyInvoke } from "tauri-plugin-pytauri-api";
import { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

export async function startTimer(
    body: Commands["start_timer"]["input"],
    options?: InvokeOptions
): Promise<Commands["start_timer"]["output"]> {
    return await pyInvoke("start_timer", body, options);
};

export async function greet(
    body: Commands["greet"]["input"],
    options?: InvokeOptions
): Promise<Commands["greet"]["output"]> {
    return await pyInvoke("greet", body, options);
};

