"""Original FFI interface module.

!!! warning
    All APIs under this module should not be considered stable.
    You should use the re-exported APIs under the top-level module.
"""

from pytauri.ffi._ext_mod import EXT_MOD
from pytauri.ffi.lib import (
    IS_DEV,
    RESTART_EXIT_CODE,
    VERSION,
    App,
    AppHandle,
    Assets,
    Builder,
    BuilderArgs,
    CloseRequestApi,
    Context,
    CursorIcon,
    DragDropEvent,
    DragDropEventType,
    Emitter,
    Event,
    EventId,
    EventTarget,
    EventTargetType,
    ExitRequestApi,
    ImplEmitter,
    ImplListener,
    ImplManager,
    Listener,
    LogicalRect,
    Manager,
    PhysicalRect,
    Position,
    PositionType,
    Rect,
    RunEvent,
    RunEventType,
    Size,
    SizeType,
    Theme,
    Url,
    UserAttentionType,
    WebviewEvent,
    WebviewEventType,
    WindowEvent,
    WindowEventType,
    builder_factory,
    context_factory,
    webview_version,
)

__all__ = (
    "EXT_MOD",
    "IS_DEV",
    "RESTART_EXIT_CODE",
    "VERSION",
    "App",
    "AppHandle",
    "Assets",
    "Builder",
    "BuilderArgs",
    "CloseRequestApi",
    "Context",
    "CursorIcon",
    "DragDropEvent",
    "DragDropEventType",
    "Emitter",
    "Event",
    "EventId",
    "EventTarget",
    "EventTargetType",
    "ExitRequestApi",
    "ImplEmitter",
    "ImplListener",
    "ImplManager",
    "Listener",
    "LogicalRect",
    "Manager",
    "PhysicalRect",
    "Position",
    "PositionType",
    "Rect",
    "RunEvent",
    "RunEventType",
    "Size",
    "SizeType",
    "Theme",
    "Url",
    "UserAttentionType",
    "WebviewEvent",
    "WebviewEventType",
    "WindowEvent",
    "WindowEventType",
    "builder_factory",
    "context_factory",
    "webview_version",
)
