# "$schema" = "../gen/schemas/desktop-schema.json"  # we do not support this feature yet
identifier = "default"
description = "Capability for the main window"
windows = ["main"]
permissions = [
    "core:default",
    "pytauri:default",
    "notification:default",
    "dialog:default",
    "clipboard-manager:default",
    "fs:default",
    "opener:default",
    "autostart:default",
    "deep-link:default",
    "http:default",
    "os:default",
    "positioner:default",
    "process:default",
    "shell:default",
    "updater:default",
    "upload:default",
    "websocket:default",
    "window-state:default",
    "global-shortcut:default",
]
