# copy from: https://github.com/fastapi-users/fastapi-users/blob/v14.0.1/.github/workflows/documentation.yml

# WARNING: Do not change the name of this file, keep `docs.yml`.
# markdown badges are hard-coded to point to this file.

name: Deploy documentation

# Since document updates may be frequent,
# we do not run tests when deploying documents,
# instead test during the PR stage.
on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for `mike --push`
    environment:
      name: github-pages
    steps:
      - name: Parse tag
        id: version_tag
        uses: battila7/get-version-action@v2
      - name: Check if is semver tag
        if: startsWith(github.ref, 'refs/tags/v') && steps.version_tag.outputs.is-semver != 'true'
        run: |
          echo "`${{ github.ref }}` is not a valid semver tag."
          exit 1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # see: <https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/tree/2e7646ee3405d8793e5ebb83eb45f7aa9407b205?tab=readme-ov-file#note-when-using-build-systems-like-github-actions>
          fetch-depth: 0
      - name: setup-envs-ver
        id: setup-envs-ver
        uses: ./.github/actions/setup-envs-ver
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          # see: <https://docs.astral.sh/uv/guides/integration/github/>
          version: ${{ steps.setup-envs-ver.outputs.uv }}
          enable-cache: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      # see: <https://github.com/jimporter/mike/tree/v2.1.3?tab=readme-ov-file#deploying-via-ci>
      - name: Set git credentials
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin gh-pages --depth=1
      - name: Deploy docs
        env:
          DOC_TAG: ${{ steps.version_tag.outputs.major && steps.version_tag.outputs.minor && format('{0}.{1} latest', steps.version_tag.outputs.major, steps.version_tag.outputs.minor) || 'dev' }}
          # skip building pytauri extension module file, see `python/pytauri-wheel/setup.py`
          # (because we don't need running these workspaces python packages when building docs,
          # and we don't have tauri system dependencies in the Linux CI)
          PYTAURI_STANDALONE: 1
        run: |
          uv run --only-group=docs --only-group=workspaces --all-extras -- \
              mike deploy --push --update-aliases ${{ env.DOC_TAG }}
